#!/bin/sh

PID=$(lsof -w /dev/snd/pcm*c | wc -c)

if [[ $PID -eq 0 ]]
then
  echo ""
else
    if [[ $(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep "[MUTED]" | wc -l) -eq 0 ]]
    then
        echo "󰍬"
    else
        echo "󰍭"
    fi
fi
